//! Native utilities exported via N-API for the Oh My Pi toolchain.
//!
//! # Overview
//! High-performance primitives for clipboard access, grep, file discovery,
//! ANSI-aware text measurement, syntax highlighting, HTML-to-Markdown
//! conversion, and terminal SIXEL encoding.
//!
//! # Example
//! ```ignore
//! use pi_natives::text::visible_width;
//!
//! let width = visible_width("hello");
//! assert_eq!(width, 5);
//! ```
//!
//! # Architecture
//! ```text
//! JS (packages/natives) -> N-API -> Rust modules (clipboard/fd/glob/grep/html/highlight/sixel/text)
//! ```

#![allow(clippy::trailing_empty_array, reason = "generated by napi macro")]
#![allow(clippy::trivially_copy_pass_by_ref, reason = "napi env idiom")]
#![feature(alloc_error_hook)]

pub mod appearance;
pub mod ast;
pub mod block;
pub mod clipboard;
pub mod crash_handler;
pub mod fd;
pub mod fs_cache;
pub mod glob;
pub mod glob_util;
pub mod grep;
pub mod highlight;
pub mod html;
pub mod keys;
pub mod sixel;
pub mod snapcompact;
pub use pi_ast::language;

pub mod power;

pub mod iso;
pub mod prof;
pub mod ps;
pub mod pty;
pub mod shell;
pub mod summary;
pub mod task;
pub mod text;
pub mod tokens;
pub(crate) mod utils;
pub mod workspace;

#[cfg(target_os = "windows")]
use std::sync::{
	Arc,
	atomic::{AtomicBool, Ordering},
};

#[cfg(target_os = "windows")]
use napi::bindgen_prelude::create_custom_tokio_runtime;
use napi_derive::{module_init, napi};

/// Upper bound on Windows Tokio *scheduler* workers. These only drive async I/O
/// futures (shell/process/PTY/ISO) and light glue tasks; all CPU-heavy and
/// blocking native work runs elsewhere — libuv tasks (`task::blocking`), Rayon,
/// or Tokio's separate blocking pool via `spawn_blocking` — so a handful of
/// async workers is plenty regardless of core count.
#[cfg(target_os = "windows")]
const NAPI_TOKIO_MAX_WORKER_THREADS: usize = 4;
/// Cap on Tokio's lazily-grown blocking pool (used by `spawn_blocking` offloads
/// such as `iso_start`/`iso_stop`/`pty.start`/`walk_diff`). Threads here are
/// created on demand, not at load, so this only bounds peak fan-out.
#[cfg(target_os = "windows")]
const NAPI_TOKIO_MAX_BLOCKING_THREADS: usize = 8;

/// Windows worker count we'd *like*, before checking what the OS will actually
/// grant: the Tokio default (one per core) clamped to
/// [`NAPI_TOKIO_MAX_WORKER_THREADS`].
#[cfg(target_os = "windows")]
fn desired_worker_threads() -> usize {
	std::thread::available_parallelism()
		.map_or(1, |threads| threads.get())
		.clamp(1, NAPI_TOKIO_MAX_WORKER_THREADS)
}

/// Probe how many worker threads Windows will let us hold alive
/// *simultaneously*, up to `target`. Returns the count actually spawned (0 when
/// not even one extra thread is possible).
///
/// `Builder::build()` for a multi-thread runtime spawns every worker eagerly
/// and **panics** (not `Err`) when Windows refuses one — on a
/// memory-constrained host (tiny pagefile / commit limit, `os error 1455`) that
/// aborts the whole process at addon load before any JS error can surface. The
/// release profile is `panic = "abort"`, so the panic can't even be caught. We
/// instead pre-flight with `std::thread::Builder::spawn`, which returns an
/// `io::Result`, holding each probe thread alive (so their stacks are committed
/// concurrently, matching how real workers coexist) until we know the safe
/// count. Probe threads use the std default stack, exactly like Tokio's workers
/// (it leaves `thread_stack_size` unset), so the probe is representative.
///
/// Keep this Windows-only. On Linux, spawning probe threads from `module_init`
/// can deadlock while Bun is loading the `.node`; napi-rs's default runtime
/// loads cleanly there and avoids any custom loader-time thread probe.
#[cfg(target_os = "windows")]
fn probe_spawnable_workers(target: usize) -> usize {
	let keep_running = Arc::new(AtomicBool::new(true));
	let mut handles = Vec::with_capacity(target);
	for _ in 0..target {
		let keep = Arc::clone(&keep_running);
		match std::thread::Builder::new().spawn(move || {
			while keep.load(Ordering::Relaxed) {
				std::thread::park_timeout(std::time::Duration::from_millis(1));
			}
		}) {
			Ok(handle) => handles.push(handle),
			Err(_) => break,
		}
	}
	let spawned = handles.len();
	keep_running.store(false, Ordering::Relaxed);
	for handle in handles {
		handle.thread().unpark();
		let _ = handle.join();
	}
	spawned
}

/// Build the custom Tokio runtime napi-rs uses on Windows, sized to what the
/// host can actually spawn. Never panics: backs off from
/// [`desired_worker_threads`] to whatever the probe allows, and falls back to a
/// current-thread runtime (which spawns no workers at build time, so it can't
/// abort under commit-limit pressure) when not even one worker is available.
/// Returns `None` only if even that fails, in which case we leave napi-rs to
/// construct its own default.
#[cfg(target_os = "windows")]
fn create_windows_napi_tokio_runtime() -> Option<tokio::runtime::Runtime> {
	let workers = probe_spawnable_workers(desired_worker_threads());
	let multi_thread = (workers > 0)
		.then(|| {
			tokio::runtime::Builder::new_multi_thread()
				.worker_threads(workers)
				.max_blocking_threads(NAPI_TOKIO_MAX_BLOCKING_THREADS)
				.enable_all()
				.build()
				.ok()
		})
		.flatten();
	multi_thread.or_else(|| {
		tokio::runtime::Builder::new_current_thread()
			.enable_all()
			.build()
			.ok()
	})
}

/// Version sentinel — exists solely so the JS loader can prove at load time
/// that the `.node` file on disk is from the same package release as the
/// `index.js` ESM wrapper invoking it.
///
/// The `js_name` is bumped by `scripts/release.ts` to match the new
/// `Cargo.toml` / `package.json` version on every release. The JS loader
/// computes the expected name from `package.json#version` and refuses to use
/// a `.node` that doesn't expose it, turning the silent
/// `<sym> is not a function` crash from a locked-file update (the canonical
/// Windows `bun install -g` failure mode) into a clear load-time error.
///
/// Bump policy: `__piNativesV{major}_{minor}_{patch}` — non-alphanumerics in
/// the version string are mapped to `_` to keep it a valid JS identifier.
/// MUST stay in sync with `VERSION_SENTINEL_EXPORT` in
/// `packages/natives/native/index.js` (which derives the name from
/// `package.json#version`).
#[napi(js_name = "__piNativesV15_12_6")]
pub const fn pi_natives_version_sentinel() {}

/// Native module entry point: install crash diagnostics before any tool can
/// invoke a panicking or allocating native call. This runs during `.node`
/// load, while the dynamic-loader lock is held, so it MUST NOT spawn threads —
/// the Tokio runtime is installed afterwards on Windows by
/// [`omp_install_tokio_runtime`], which the JS loader calls once `dlopen` has
/// returned.
///
/// On Windows, the custom Tokio runtime is host-sized to prevent aborts under
/// memory limits (see [`create_windows_napi_tokio_runtime`]). Non-Windows
/// builds intentionally use napi-rs's default path. Linux source builds can
/// deadlock if this module initializer or post-load setup performs its own
/// thread probe, so we keep the probe and custom runtime Windows-only.
#[module_init]
fn install_native_crash_handler() {
	crash_handler::install();
}

/// Guards [`omp_install_tokio_runtime`] so the runtime is built at most once
/// per process even if the loader invokes it more than once.
#[cfg(target_os = "windows")]
static TOKIO_RUNTIME_INSTALLED: AtomicBool = AtomicBool::new(false);

/// Install the bounded Tokio runtime napi-rs adopts for async exports.
///
/// The JS loader calls this exactly once, synchronously, right *after* `dlopen`
/// returns and *before* any async native runs — never from `#[module_init]`.
/// Building a multi-thread runtime eagerly spawns worker threads, and doing
/// that during module init (while the dynamic-loader lock is held) deadlocks on
/// some hosts: a fresh worker blocks acquiring the loader lock that the init
/// thread still owns. napi-rs only materializes its runtime on the first async
/// call (`RT` is a `LazyLock`) and `create_custom_tokio_runtime` merely records
/// the runtime in a `OnceLock`, so installing it post-load is still honored.
/// Without it napi builds its own default (one worker per CPU, spawned eagerly)
/// which aborts the process (`os error 1455`) on a memory-constrained Windows
/// host before any JS error can surface; [`create_windows_napi_tokio_runtime`]
/// pre-flights the spawn instead. If no runtime can be built we leave napi-rs
/// to its default. Idempotent.
#[napi(js_name = "__ompInstallTokioRuntime")]
pub const fn omp_install_tokio_runtime() {
	#[cfg(target_os = "windows")]
	if TOKIO_RUNTIME_INSTALLED.swap(true, Ordering::SeqCst) {
		return;
	}
	#[cfg(target_os = "windows")]
	if let Some(runtime) = create_windows_napi_tokio_runtime() {
		create_custom_tokio_runtime(runtime);
	}
}
